// <auto-generated />
using System;
using BffOrchestratorService.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BffOrchestratorService.Persistence.Migrations
{
    [DbContext(typeof(BffOrchestratorDbContext))]
    [Migration("20260529063301_ProcessRuntimeOutbox")]
    partial class ProcessRuntimeOutbox
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BffOrchestratorService.Domain.Entities.BusinessProcessState", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("Id");

                    b.Property<string>("AggregateId")
                        .HasColumnType("text")
                        .HasColumnName("aggregate_id");

                    b.Property<bool>("AwaitingClientDecision")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("awaiting_client_decision");

                    b.Property<string>("CausationId")
                        .HasColumnType("text")
                        .HasColumnName("causation_id");

                    b.Property<DateTimeOffset?>("ClientDecisionDeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("client_decision_deadline_at");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("correlation_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("CurrentStepName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("created")
                        .HasColumnName("current_step_name");

                    b.Property<int>("CurrentStepOrdinal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("current_step_ordinal");

                    b.Property<string>("FlowType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flow_type");

                    b.Property<DateTimeOffset?>("HeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("heartbeat_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("InputPayload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("input_payload")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTimeOffset>("IntentPersistedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("intent_persisted_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("InterruptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("interrupted_at");

                    b.Property<string>("LastErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("last_error_code");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("last_error_message");

                    b.Property<DateTimeOffset?>("LeaseAcquiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_acquired_at");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("text")
                        .HasColumnName("lease_owner");

                    b.Property<int>("MaxRetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(20)
                        .HasColumnName("max_retry_count");

                    b.Property<DateTimeOffset>("NextVisibleAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_visible_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ProcessContext")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("process_context")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("ProcessKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("process_key");

                    b.Property<string>("ProcessName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("process_name");

                    b.Property<string>("RecoveryPolicy")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recovery_policy");

                    b.Property<DateTimeOffset?>("ResponseCommittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("response_committed_at");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<string>("ResultPayload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("result_payload")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("retry_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SyncDeadlineAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sync_deadline_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_business_process_state_correlation");

                    b.HasIndex("LeaseExpiresAt")
                        .HasDatabaseName("ix_business_process_state_lease_expiry")
                        .HasFilter("lease_expires_at is not null");

                    b.HasIndex("ProcessName", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_business_process_state_name_idempotency");

                    b.HasIndex("ProcessKey", "NextVisibleAt", "Id")
                        .HasDatabaseName("ix_business_process_state_process_key_active")
                        .HasFilter("status in ('started', 'in_progress', 'waiting', 'retrying', 'compensating', 'interrupted', 'paused')");

                    b.ToTable("business_process_state", null, t =>
                        {
                            t.HasCheckConstraint("ck_business_process_state_current_step_ordinal", "current_step_ordinal >= 0");

                            t.HasCheckConstraint("ck_business_process_state_flow_type", "flow_type in ('synchronous', 'asynchronous')");

                            t.HasCheckConstraint("ck_business_process_state_max_retry_count", "max_retry_count >= 0");

                            t.HasCheckConstraint("ck_business_process_state_recovery_policy", "recovery_policy in ('resume_on_restart', 'alert_client_and_pause', 'escalate_and_stop')");

                            t.HasCheckConstraint("ck_business_process_state_retry_count", "retry_count >= 0");

                            t.HasCheckConstraint("ck_business_process_state_status", "status in ('started', 'in_progress', 'waiting', 'interrupted', 'retrying', 'compensating', 'completed', 'failed', 'escalated', 'paused')");

                            t.HasCheckConstraint("ck_business_process_state_version", "version > 0");
                        });
                });

            modelBuilder.Entity("BffOrchestratorService.Domain.Entities.ProcessCheckpoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("CheckpointData")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("checkpoint_data")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("CheckpointKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("checkpoint_kind");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("DispatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("dispatch_id");

                    b.Property<string>("ExternalReference")
                        .HasColumnType("text")
                        .HasColumnName("external_reference");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("MessageKey")
                        .HasColumnType("text")
                        .HasColumnName("message_key");

                    b.Property<string>("ObservedOutcome")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("observed_outcome");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<string>("StepName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("step_name");

                    b.Property<int>("StepOrdinal")
                        .HasColumnType("integer")
                        .HasColumnName("step_ordinal");

                    b.HasKey("Id");

                    b.HasIndex("ExternalReference")
                        .HasDatabaseName("ix_process_checkpoint_external_reference")
                        .HasFilter("external_reference is not null");

                    b.HasIndex("ProcessId", "CheckpointKind", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_process_checkpoint_process_kind_idempotency");

                    b.HasIndex("ProcessId", "StepOrdinal", "CreatedAt")
                        .HasDatabaseName("ix_process_checkpoint_process_step");

                    b.ToTable("process_checkpoint", null, t =>
                        {
                            t.HasCheckConstraint("ck_process_checkpoint_kind", "checkpoint_kind in ('dispatch', 'reservation_recorded', 'validation_succeeded', 'commit_dispatched', 'commit_succeeded', 'reservation_cancel_dispatched', 'reservation_cancel_succeeded', 'step_failed', 'retry_scheduled', 'timeout', 'paused', 'interrupted', 'client_decision', 'resumed', 'completed', 'cancelled')");

                            t.HasCheckConstraint("ck_process_checkpoint_observed_outcome", "observed_outcome in ('pending', 'reserved', 'validated', 'committed', 'failed', 'timed_out', 'reservation_cancelled', 'paused', 'interrupted', 'approved', 'rejected', 'cancelled')");

                            t.HasCheckConstraint("ck_process_checkpoint_step_ordinal", "step_ordinal >= 0");
                        });
                });

            modelBuilder.Entity("BffOrchestratorService.Domain.Entities.ProcessQueueItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("Id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("AttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dedupe_key");

                    b.Property<string>("FlowType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("flow_type");

                    b.Property<string>("LastErrorCode")
                        .HasColumnType("text")
                        .HasColumnName("last_error_code");

                    b.Property<string>("LastErrorMessage")
                        .HasColumnType("text")
                        .HasColumnName("last_error_message");

                    b.Property<DateTimeOffset?>("LeaseAcquiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_acquired_at");

                    b.Property<DateTimeOffset?>("LeaseExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lease_expires_at");

                    b.Property<string>("LeaseOwner")
                        .HasColumnType("text")
                        .HasColumnName("lease_owner");

                    b.Property<int>("MaxAttemptCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(20)
                        .HasColumnName("max_attempt_count");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<short>("Priority")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)100)
                        .HasColumnName("priority");

                    b.Property<Guid>("ProcessId")
                        .HasColumnType("uuid")
                        .HasColumnName("process_id");

                    b.Property<string>("ProcessKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("process_key");

                    b.Property<long>("SequenceNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_no");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("SequenceNo"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("ready")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset>("VisibleAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("visible_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("WorkType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("work_type");

                    b.HasKey("Id");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("ux_process_queue_dedupe_key");

                    b.HasIndex("LeaseExpiresAt")
                        .HasDatabaseName("ix_process_queue_lease_expiry")
                        .HasFilter("status = 'leased'");

                    b.HasIndex("ProcessId");

                    b.HasIndex("Status", "VisibleAt", "Priority", "SequenceNo")
                        .HasDatabaseName("ix_process_queue_ready_dequeue")
                        .HasFilter("status = 'ready'");

                    b.HasIndex("ProcessKey", "Status", "Priority", "VisibleAt", "SequenceNo")
                        .HasDatabaseName("ix_process_queue_process_key_head");

                    b.ToTable("process_queue", null, t =>
                        {
                            t.HasCheckConstraint("ck_process_queue_attempt_count", "attempt_count >= 0");

                            t.HasCheckConstraint("ck_process_queue_flow_type", "flow_type in ('synchronous', 'asynchronous')");

                            t.HasCheckConstraint("ck_process_queue_max_attempt_count", "max_attempt_count >= 0");

                            t.HasCheckConstraint("ck_process_queue_status", "status in ('ready', 'leased', 'completed', 'dead_letter', 'cancelled')");

                            t.HasCheckConstraint("ck_process_queue_work_type", "work_type in ('start', 'retry', 'resume', 'timeout', 'cancel_reservations', 'event_observation', 'client_decision', 'escalation')");
                        });
                });

            modelBuilder.Entity("BffOrchestratorService.Domain.Entities.ProcessRuntimeOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AggregateId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<int>("EventVersion")
                        .HasColumnType("integer");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("LastAttemptAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PartitionKey")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<Guid?>("TransactionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.HasIndex("Status", "OccurredAtUtc");

                    b.ToTable("outbox_messages", (string)null);
                });

            modelBuilder.Entity("BffOrchestratorService.Domain.Entities.ProcessCheckpoint", b =>
                {
                    b.HasOne("BffOrchestratorService.Domain.Entities.BusinessProcessState", null)
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BffOrchestratorService.Domain.Entities.ProcessQueueItem", b =>
                {
                    b.HasOne("BffOrchestratorService.Domain.Entities.BusinessProcessState", null)
                        .WithMany()
                        .HasForeignKey("ProcessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
