apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-api
  namespace: digitrade
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-api
  template:
    metadata:
      labels:
        app: order-api
    spec:
      containers:
        - name: order-api
          image: order-api:dev
          imagePullPolicy: Never
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: DOTNET_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS
              value: http://0.0.0.0:8080
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.digitrade.svc.cluster.local:4317
            - name: OTEL_EXPORTER_OTLP_PROTOCOL
              value: grpc
            - name: ORDER_DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: digitrade-secrets
                  key: ORDER_DB_CONNECTION
                  optional: true
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
          readinessProbe:
            httpGet:
              path: /health/ready
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 3
            failureThreshold: 6
---
apiVersion: v1
kind: Service
metadata:
  name: order-api
  namespace: digitrade
spec:
  selector:
    app: order-api
  ports:
    - name: http
      port: 8080
      targetPort: 8080
